[expenses]
recordType
formTypeCd
schedFormTypeCd
reportInfoIdent
receivedDt
infoOnlyFlag
filerIdent
filerTypeCd
filerName
expendInfoId
expendDt
expendAmount
expendDescr
expendCatCd
expendCatDescr
itemizeFlag
travelFlag
politicalExpendCd
reimburseIntendedFlag
srcCorpContribFlag
capitalLivingexpFlag
payeePersentTypeCd
payeeNameOrganization
payeeNameLast
payeeNameSuffixCd
payeeNameFirst
payeeNamePrefixCd
payeeNameShort
payeeStreetAddr1
payeeStreetAddr2
payeeStreetCity
payeeStreetStateCd

payeeStreetCountyCd
payeeStreetCountryCd
payeeStreetPostalCode
payeeStreetRegion
creditCardIssuer
repaymentDt


[contributions]
recordType
formTypeCd
schedFormTypeCd
reportInfoIdent
receivedDt
infoOnlyFlag
filerIdent
filerTypeCd
filerName
contributionInfoId
contributionDt
contributionAmount
contributionDescr
itemizeFlag
travelFlag
contributorPersentTypeCd
contributorNameOrganization
contributorNameLast
contributorNameSuffixCd
contributorNameFirst
contributorNamePrefixCd
contributorNameShort
contributorStreetCity
contributorStreetStateCd

contributorStreetCountyCd
contributorStreetCountryCd
contributorStreetPostalCode
contributorStreetRegion
contributorEmployer
contributorOccupation
contributorJobTitle
contributorPacFein
contributorOosPacFlag
contributorLawFirmName
contributorSpouseLawFirmName
contributorParent1LawFirmName
contributorParent2LawFirmName

[filers]
recordType
filerIdent
filerTypeCd
filerName
unexpendContribFilerFlag
modifiedElectCycleFlag
filerJdiCd
committeeStatusCd
ctaSeekOfficeCd
ctaSeekOfficeDistrict
ctaSeekOfficePlace
ctaSeekOfficeDescr
ctaSeekOfficeCountyCd
ctaSeekOfficeCountyDescr
filerPersentTypeCd
filerNameOrganization
filerNameLast
filerNameSuffixCd
filerNameFirst
filerNamePrefixCd
filerNameShort
filerStreetAddr1
filerStreetAddr2
filerStreetCity
filerStreetStateCd

filerStreetCountyCd
filerStreetCountryCd
filerStreetPostalCode
filerStreetRegion
filerMailingAddr1
filerMailingAddr2
filerMailingCity
filerMailingStateCd

filerMailingCountyCd
filerStreetCountryCd
filerMailingPostalCode
filerMailingRegion
filerPrimaryUsaPhoneFlag

filerPrimaryPhoneNumber
filerPrimaryPhoneExt
filerHoldOfficeCd
filerHoldOfficeDistrict
filerHoldOfficePlace
filerHoldOfficeDescr
filerHoldOfficeCountyCd
filerHoldOfficeCountyDescr
filerFilerpersStatusCd
filerEffStartDt
filerEffStopDt
contestSeekOfficeCd
contestSeekOfficeDistrict
contestSeekOfficePlace
contestSeekOfficeDescr
contestSeekOfficeCountyCd
contestSeekOfficeCountyDescr
treasPersentTypeCd
treasNameOrganization
treasNameLast
treasNameSuffixCd
treasNameFirst
treasNamePrefixCd
treasNameShort
treasStreetAddr1
treasStreetAddr2
treasStreetCity
treasStreetStateCd

treasStreetCountyCd
treasStreetCountryCd
treasStreetPostalCode
treasStreetRegion
treasMailingAddr1
treasMailingAddr2
treasMailingCity
treasMailingStateCd

treasMailingCountyCd
treasMailingCountryCd
treasMailingPostalCode
treasMailingRegion
treasPrimaryUsaPhoneFlag

treasPrimaryPhoneNumber
treasPrimaryPhoneExt
treasAppointorNameLast
treasAppointorNameFirst
treasFilerpersStatusCd
treasEffStartDt
treasEffStopDt
assttreasPersentTypeCd
assttreasNameOrganization
assttreasNameLast
assttreasNameSuffixCd
assttreasNameFirst
assttreasNamePrefixCd
assttreasNameShort
assttreasStreetAddr1
assttreasStreetAddr2
assttreasStreetCity
assttreasStreetStateCd

assttreasStreetCountyCd
assttreasStreetCountryCd
assttreasStreetPostalCode

assttreasStreetRegion
assttreasPrimaryUsaPhoneFlag

assttreasPrimaryPhoneNumber
assttreasPrimaryPhoneExt
assttreasAppointorNameLast
assttreasAppointorNameFirst
chairPersentTypeCd
chairNameOrganization
chairNameLast
chairNameSuffixCd
chairNameFirst
chairNamePrefixCd
chairNameShort
chairStreetAddr1
chairStreetAddr2
chairStreetCity
chairStreetStateCd

chairStreetCountyCd
chairStreetCountryCd
chairStreetPostalCode
chairStreetRegion
chairMailingAddr1
chairMailingAddr2
chairMailingCity
chairMailingStateCd

chairMailingCountyCd
chairMailingCountryCd
chairMailingPostalCode
chairMailingRegion
chairPrimaryUsaPhoneFlag

chairPrimaryPhoneNumber
chairPrimaryPhoneExt

[direct-expenditures]
recordType
formTypeCd
schedFormTypeCd
reportInfoIdent
receivedDt
infoOnlyFlag
filerIdent
filerTypeCd
filerName
expendInfoId
expendPersentId
expendDt
expendAmount
expendDescr
expendCatCd
expendCatDescr
itemizeFlag
politicalExpendCd
reimburseIntendedFlag
srcCorpContribFlag
capitalLivingexpFlag
candidatePersentTypeCd
candidateNameOrganization
candidateNameLast
candidateNameSuffixCd
candidateNameFirst
candidateNamePrefixCd
candidateNameShort
candidateHoldOfficeCd
candidateHoldOfficeDistrict
candidateHoldOfficePlace
candidateHoldOfficeDescr
candidateHoldOfficeCountyCd
candidateHoldOfficeCountyDescr
candidateSeekOfficeCd
candidateSeekOfficeDistrict
candidateSeekOfficePlace
candidateSeekOfficeDescr
candidateSeekOfficeCountyCd
candidateSeekOfficeCountyDescr