[project]
name = "campaignfinance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.8"
dependencies = [
    "aiocsv>=1.3.2",
    "aiofiles>=24.1.0",
    "aiojobs>=1.3.0",
    "icecream>=2.1.3",
    "inject>=5.2.1",
    "nameparser>=1.1.3",
    "onepassword-sdk>=0.1.5",
    "pandas>=2.2.3",
    "phonenumbers>=8.13.52",
    "probablepeople>=0.5.6",
    "pydantic>=2.10.4",
    "pydantic-extra-types>=2.10.1",
    "pydantic-settings>=2.7.0",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "selenium>=4.27.1",
    "sqlmodel>=0.0.22",
    "tomli>=2.2.1",
    "tqdm>=4.67.1",
    "usaddress-scourgify>=0.6.0",
    "usaddress>=0.5.11",
]

[tool.uv.workspace]
members = ["packages/*"]
