{#  PLDG → one CONTRIBUTOR (pledger) + committee (recipient). #}
with src as (select * from {{ source('silver', 'tx_pledges') }})
select
    'PLDG'                                      as record_type,
    'PLEDGE'                                    as transaction_type,
    'CONTRIBUTOR'                               as role,
    {{ var('state_id') }}                       as state_id,
    pledgeInfoId::text                          as source_transaction_id,
    {{ cf_safe_numeric('pledgeAmount') }}       as amount,
    {{ cf_safe_date('pledgeDt') }}              as transaction_date,
    {{ cf_clean('pledgeDescr') }}               as description,
    reportInfoIdent::text                       as report_ident,
    lpad(filerIdent::text, 8, '0')              as committee_filer_id,
    {{ cf_clean('filerName') }}                 as committee_name,
    (pledgerPersentTypeCd = 'ENTITY')           as is_org,
    {{ cf_clean('pledgerNameFirst') }}          as first_name,
    cast(null as text)                          as middle_name,
    {{ cf_clean('pledgerNameLast') }}           as last_name,
    {{ cf_clean('pledgerNameSuffixCd') }}       as suffix,
    {{ cf_clean('pledgerNameOrganization') }}   as organization,
    {{ cf_clean('pledgerEmployer') }}           as employer,
    {{ cf_clean('pledgerOccupation') }}         as occupation,
    {{ cf_clean('pledgerJobTitle') }}           as job_title,
    cast(null as text)                          as street_1,
    cast(null as text)                          as street_2,
    {{ cf_clean('pledgerStreetCity') }}         as city,
    {{ cf_clean('pledgerStreetStateCd') }}      as state,
    {{ cf_clean('pledgerStreetPostalCode') }}   as zip_code,
    {{ cf_clean('pledgerStreetCountryCd') }}    as country,
    {{ cf_clean('pledgerStreetCountyCd') }}     as county,
    cast(null as text)                          as parent_transaction_type,
    cast(null as text)                          as parent_transaction_id,
    cast(null as numeric)                       as parent_amount
from src
