{#  CRED → one CONTRIBUTOR (payor) + committee (recipient). #}
with src as (select * from {{ source('silver', 'tx_credits') }})
select
    'CRED'                                      as record_type,
    'CREDIT'                                    as transaction_type,
    'CONTRIBUTOR'                               as role,
    {{ var('state_id') }}                       as state_id,
    creditInfoId::text                          as source_transaction_id,
    {{ cf_safe_numeric('creditAmount') }}       as amount,
    {{ cf_safe_date('creditDt') }}              as transaction_date,
    {{ cf_clean('creditDescr') }}               as description,
    reportInfoIdent::text                       as report_ident,
    lpad(filerIdent::text, 8, '0')              as committee_filer_id,
    {{ cf_clean('filerName') }}                 as committee_name,
    (payorPersentTypeCd = 'ENTITY')             as is_org,
    {{ cf_clean('payorNameFirst') }}            as first_name,
    cast(null as text)                          as middle_name,
    {{ cf_clean('payorNameLast') }}             as last_name,
    {{ cf_clean('payorNameSuffixCd') }}         as suffix,
    {{ cf_clean('payorNameOrganization') }}     as organization,
    cast(null as text)                          as employer,
    cast(null as text)                          as occupation,
    cast(null as text)                          as job_title,
    {{ cf_clean('payorStreetAddr1') }}          as street_1,
    {{ cf_clean('payorStreetAddr2') }}          as street_2,
    {{ cf_clean('payorStreetCity') }}           as city,
    {{ cf_clean('payorStreetStateCd') }}        as state,
    {{ cf_clean('payorStreetPostalCode') }}     as zip_code,
    {{ cf_clean('payorStreetCountryCd') }}      as country,
    {{ cf_clean('payorStreetCountyCd') }}       as county,
    cast(null as text)                          as parent_transaction_type,
    cast(null as text)                          as parent_transaction_id,
    cast(null as numeric)                       as parent_amount
from src
