{#  EXPN → one PAYEE person + committee (PAYER). Canonical wide shape. #}
with src as (select * from {{ source('silver', 'tx_expenditures') }})
select
    'EXPN'                                      as record_type,
    'EXPENDITURE'                               as transaction_type,
    'PAYEE'                                     as role,
    {{ var('state_id') }}                       as state_id,
    expendInfoId::text                          as source_transaction_id,
    {{ cf_safe_numeric('expendAmount') }}       as amount,
    {{ cf_safe_date('expendDt') }}              as transaction_date,
    {{ cf_clean('expendDescr') }}               as description,
    reportInfoIdent::text                       as report_ident,
    lpad(filerIdent::text, 8, '0')              as committee_filer_id,
    {{ cf_clean('filerName') }}                 as committee_name,
    (payeePersentTypeCd = 'ENTITY')             as is_org,
    {{ cf_clean('payeeNameFirst') }}            as first_name,
    cast(null as text)                          as middle_name,
    {{ cf_clean('payeeNameLast') }}             as last_name,
    {{ cf_clean('payeeNameSuffixCd') }}         as suffix,
    {{ cf_clean('payeeNameOrganization') }}     as organization,
    cast(null as text)                          as employer,
    cast(null as text)                          as occupation,
    cast(null as text)                          as job_title,
    {{ cf_clean('payeeStreetAddr1') }}          as street_1,
    {{ cf_clean('payeeStreetAddr2') }}          as street_2,
    {{ cf_clean('payeeStreetCity') }}           as city,
    {{ cf_clean('payeeStreetStateCd') }}        as state,
    {{ cf_clean('payeeStreetPostalCode') }}     as zip_code,
    {{ cf_clean('payeeStreetCountryCd') }}      as country,
    {{ cf_clean('payeeStreetCountyCd') }}       as county,
    cast(null as text)                          as parent_transaction_type,
    cast(null as text)                          as parent_transaction_id,
    cast(null as numeric)                       as parent_amount
from src
