"""baseline schema (full current schema via SQLModel.metadata + Fix-7 dedup indexes)

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-15

This baseline reproduces the schema the project bootstrapped via
``SQLModel.metadata.create_all`` + ``UnifiedDatabaseManager._DEDUP_INDEXES`` (the pre-Alembic
mechanism), so a fresh DB ``upgrade head`` lands byte-equal to the old bootstrap. EXISTING
databases (whose schema already matches) are marked with ``alembic stamp 0001_baseline`` rather
than upgraded. Every schema change AFTER this point is a new autogenerated/hand-written revision.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Import model modules so SQLModel.metadata is fully populated before create_all.
import app.core.models  # noqa: F401
import app.core.source_models  # noqa: F401

revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    from sqlmodel import SQLModel

    from app.core.unified_database import UnifiedDatabaseManager

    bind = op.get_bind()
    # Create every registered table (idempotent: skips tables that already exist).
    SQLModel.metadata.create_all(bind)
    # Fix-7 partial/functional unique indexes — Postgres only (lower() functional indexes;
    # _get_session / bootstrap apply them only off sqlite). IF NOT EXISTS keeps it idempotent.
    if bind.dialect.name != "sqlite":
        for ddl in UnifiedDatabaseManager._DEDUP_INDEXES:
            bind.execute(sa.text(ddl))


def downgrade() -> None:
    from sqlmodel import SQLModel

    SQLModel.metadata.drop_all(op.get_bind())
