"""
DB Size Baseline Report — Wave 0 of the DB Bloat Remediation plan.

Runs table-size, index-size, and total-DB-size queries against the local Postgres
database, prints results via Rich, and saves the output to
``docs/db-bloat-baseline-YYYY-MM-DD.md``.

Usage (from the project root):

    uv run python scripts/db_size_report.py
    uv run python scripts/db_size_report.py --output docs/my-custom-baseline.md
"""

from __future__ import annotations

import sys
from datetime import date
from pathlib import Path
from typing import Annotated

import typer
from rich.console import Console
from rich.table import Table
from sqlalchemy import text

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

console = Console()


TABLE_SIZES_SQL = """
SELECT
    c.relname                                                                         AS "table",
    pg_size_pretty(pg_total_relation_size(c.oid))                                    AS total,
    pg_size_pretty(pg_relation_size(c.oid))                                          AS heap,
    pg_size_pretty(pg_total_relation_size(c.oid) - pg_relation_size(c.oid))          AS toast_plus_idx,
    COALESCE(s.n_dead_tup, 0)                                                        AS dead_tup,
    COALESCE(s.n_live_tup, 0)                                                        AS live_tup
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
LEFT JOIN pg_stat_user_tables s ON s.relid = c.oid
WHERE c.relkind = 'r' AND n.nspname = 'public'
ORDER BY pg_total_relation_size(c.oid) DESC
LIMIT 30;
"""

INDEX_USAGE_SQL = """
SELECT
    i.relname                                                 AS index,
    t.relname                                                 AS "table",
    pg_size_pretty(pg_relation_size(i.oid))                   AS size,
    COALESCE(s.idx_scan, 0)                                   AS idx_scan
FROM pg_stat_user_indexes s
JOIN pg_class i ON i.oid = s.indexrelid
JOIN pg_class t ON t.oid = s.relid
ORDER BY pg_relation_size(i.oid) DESC;
"""

TOTAL_SIZE_SQL = """
SELECT pg_size_pretty(pg_database_size(current_database())) AS total_db_size;
"""


def _run_report(output: Path | None = None) -> None:
    from app.core.unified_database import get_db_manager

    manager = get_db_manager(bootstrap=False)

    report_lines: list[str] = []

    def _heading(title: str) -> None:
        console.rule(f"[bold cyan]{title}")
        report_lines.append(f"\n## {title}\n")

    def _query_table(label: str, sql: str, columns: list[str]) -> None:
        _heading(label)
        try:
            with manager.engine.connect() as conn:
                result = conn.execute(text(sql.strip()))
                rows = result.fetchall()

            tbl = Table(*columns, show_header=True, header_style="bold cyan")
            md_rows: list[str] = []
            header = "| " + " | ".join(columns) + " |"
            separator = "| " + " | ".join(["---"] * len(columns)) + " |"
            report_lines.append(header)
            report_lines.append(separator)

            for row in rows:
                row_vals = [str(v) if v is not None else "" for v in row]
                tbl.add_row(*row_vals)
                md_rows.append("| " + " | ".join(row_vals) + " |")

            console.print(tbl)
            report_lines.extend(md_rows)

        except Exception as exc:
            console.print(f"[red]Query failed: {exc}[/red]")
            report_lines.append(f"*Query failed: {exc}*")

    today = date.today().isoformat()
    report_lines.append(f"# DB Bloat Baseline — {today}")
    report_lines.append("")
    report_lines.append(
        "Generated by `scripts/db_size_report.py` as part of the DB Bloat Remediation plan."
    )
    report_lines.append("")

    # Total DB size
    _heading("Total DB Size")
    try:
        with manager.engine.connect() as conn:
            result = conn.execute(text(TOTAL_SIZE_SQL.strip()))
            row = result.fetchone()
            total_size = row[0] if row else "unknown"
        console.print(f"[bold green]Total DB size: {total_size}[/bold green]")
        report_lines.append(f"**Total DB size: {total_size}**")
        report_lines.append("")
    except Exception as exc:
        console.print(f"[red]Total size query failed: {exc}[/red]")
        report_lines.append(f"*Total size query failed: {exc}*")

    _query_table(
        "Table Sizes (Top 30 by total size)",
        TABLE_SIZES_SQL,
        ["table", "total", "heap", "toast_plus_idx", "dead_tup", "live_tup"],
    )

    _query_table(
        "Index Sizes and Scan Counts",
        INDEX_USAGE_SQL,
        ["index", "table", "size", "idx_scan"],
    )

    # Save report
    if output is None:
        output = ROOT / "docs" / f"db-bloat-baseline-{today}.md"

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(report_lines) + "\n", encoding="utf-8")
    console.print(f"\n[bold green]Report saved to:[/bold green] {output}")


def main(
    output: Annotated[
        Path | None,
        typer.Option("--output", "-o", help="Path to save the Markdown report."),
    ] = None,
) -> None:
    """Run the DB size baseline report and save to docs/."""
    _run_report(output=output)


if __name__ == "__main__":
    typer.run(main)
