# texas_fields.toml
[urls]
    campaign-finance-zip = "https://ethics.state.tx.us/data/search/cf/TEC_CF_CSV.zip"
[file-prefixes]
    expenses="expend"
    contributions="contrib"
    filers = "filer"
    reports = "finals"
    travel = "travel"
    candidates = "cand"
    debts = "debts"
    loans = "loans"
