from states.texas.database import Base
from sqlalchemy import Column, ForeignKey, Integer, String, text, Float, Boolean, Date


class TECExpenseRecord(Base):
    __tablename__ = "texas.expenses"

    recordType = Column(String, nullable=False)
    formTypeCd = Column(String, nullable=False)
    schedFormTypeCd = Column(String, nullable=False)
    reportInfoIdent = Column(Integer, nullable=False)
    receivedDt = Column(Date, nullable=False)
    infoOnlyFlag = Column(Boolean, nullable=True)
    filerIdent = Column(Integer, nullable=False)
    filerTypeCd = Column(String, nullable=False)
    filerName = Column(String, nullable=False)
    expendInfoId = Column(Integer, nullable=False, primary_key=True)
    expendDt = Column(Date, nullable=False)
    expendAmount = Column(Float, nullable=False)
    expendDescr = Column(String, nullable=False)
    expendCatCd = Column(String, nullable=False)
    expendCatDescr = Column(String, nullable=False)
    itemizeFlag = Column(Boolean, nullable=True)
    travelFlag = Column(Boolean, nullable=True)
    politicalExpendCd = Column(String, nullable=True)
    reimburseIntendedFlag = Column(String, nullable=True)
    srcCorpContribFlag = Column(String, nullable=True)
    capitalLivingexpFlag = Column(String, nullable=True)
    payeePersentTypeCd = Column(String, nullable=False)
    payeeNameOrganization = Column(String, nullable=True)
    payeeNameLast = Column(String, nullable=True)
    payeeNameSuffixCd = Column(String, nullable=True)
    payeeNameFirst = Column(String, nullable=True)
    payeeNamePrefixCd = Column(String, nullable=True)
    payeeNameShort = Column(String, nullable=True)
    payeeStreetAddr1 = Column(String, nullable=False)
    payeeStreetAddr2 = Column(String, nullable=True)
    payeeStreetCity = Column(String, nullable=False)
    payeeStreetStateCd = Column(String, nullable=False)
    payeeStreetCountyCd = Column(String, nullable=False)
    payeeStreetCountryCd = Column(String, nullable=False)
    payeeStreetPostalCode = Column(String, nullable=True)
    payeeStreetRegion = Column(String, nullable=True)
    creditCardIssuer = Column(String, nullable=True)
    repaymentDt = Column(Date, nullable=True)
    filer_id = Column(Integer, nullable=False)
    contributions_id = Column(Integer, nullable=False)
