name: Run Texas Download

on:
  push:
    branches: [ main, master ]

jobs:
  run-texas-download:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Lock dependencies
      run: |
        poetry lock --no-update

    - name: Install dependencies
      run: |
        poetry install

    - name: Run script
      run: poetry run python app/workflows/texas_download.py